load("@rules_python//python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "client_lib",
    srcs = ["main.py"],
    imports = ["."],
    deps = [
        "//clients/python:castor_client",
    ],
)

py_test(
    name = "test_python_client_example",
    size = "small",
    srcs = ["test_client.py"],
    imports = ["."],
    main = "test_client.py",
    deps = [":client_lib"],
)
