load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "docs_lib",
    srcs = ["docs.py"],
    imports = ["../.."],
)

py_binary(
    name = "docs",
    srcs = ["docs.py"],
    data = [
        "//:docs_data",
        "//:skills_data",
    ],
    main = "docs.py",
    deps = [":docs_lib"],
)

py_test(
    name = "test_docs",
    size = "small",
    srcs = ["test_docs.py"],
    main = "test_docs.py",
    deps = [":docs_lib"],
)
