apiVersion: v1
kind: ConfigMap
metadata:
  name: castor-registry-config
  namespace: castor
data:
  APP_ENV: "qa"
  MODENV_ENV: "qa"
  EMBEDDING_PROVIDER: "alloydb-ai"
  OTEL_SERVICE_NAME: "castor-registry-qa"
