apiVersion: apps/v1
kind: Deployment
metadata:
  name: castor-registry
  namespace: castor
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: castor-registry
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
