apiVersion: v1
kind: ConfigMap
metadata:
  name: castor-registry-config
  namespace: castor
data:
  APP_ENV: "production"
  MODENV_ENV: "production"
  EMBEDDING_PROVIDER: "vertex-gemini"
  OTEL_SERVICE_NAME: "castor-registry-prod"
