apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: castor-registry-hpa
  namespace: castor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: castor-registry
  minReplicas: 5
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
