apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-service
  namespace: skill-builder
spec:
  replicas: 5
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: skill-service
      containers:
        - name: skill-service
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
