apiVersion: apps/v1
kind: Deployment
metadata:
  name: castor-registry
  namespace: castor
spec:
  replicas: 5
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: castor-registry
      containers:
        - name: castor-registry
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
