package(default_visibility = ["//visibility:public"])

test_suite(
    name = "test_skills_e2e",
    tests = [
        "//tests/e2e:test_skills_e2e",
    ],
)

test_suite(
    name = "e2e",
    tests = [
        "//tests/e2e:test_skills_e2e",
    ],
)

test_suite(
    name = "integration",
    tags = [
        "integration",
        "manual",
    ],
    tests = [
        "//pkg/embedding:embedding_integration_test",
    ],
)
