// Copyright 2026 Ryan McGuinness
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package castor_client

import (
	"sort"
)

// AuthorDetails represents structured attribution for a skill contributor.
type AuthorDetails struct {
	Name  string `json:"name,omitempty"`
	Email string `json:"email,omitempty"`
	URL   string `json:"url,omitempty"`
}

// ToolRequirement represents a structured permission contract for agent tool execution.
type ToolRequirement struct {
	Name        string   `json:"name"`
	Scopes      []string `json:"scopes,omitempty"`
	Description string   `json:"description,omitempty"`
}

// ExecutionHints provides operational parameters for LLM agents, routers, and orchestrators.
type ExecutionHints struct {
	PreferredModel        string            `json:"preferred_model,omitempty"`
	RequiresHumanApproval bool              `json:"requires_human_approval,omitempty"`
	EnvironmentVariables  []string          `json:"environment_variables,omitempty"`
	TimeoutSeconds        int               `json:"timeout_seconds,omitempty"`
	CustomHints           map[string]string `json:"custom_hints,omitempty"`
}

// ScriptLanguage defines supported execution runtimes for skill helper scripts.
type ScriptLanguage string

const (
	ScriptLanguageUnspecified ScriptLanguage = "SCRIPT_LANGUAGE_UNSPECIFIED"
	ScriptLanguagePython      ScriptLanguage = "SCRIPT_LANGUAGE_PYTHON"
	ScriptLanguageTypeScript  ScriptLanguage = "SCRIPT_LANGUAGE_TYPESCRIPT"
)

// ScriptDefinition specifies an executable helper script attached to a skill.
type ScriptDefinition struct {
	Name                 string            `json:"name"`
	Description          string            `json:"description,omitempty"`
	Language             ScriptLanguage    `json:"language"`
	InlineCode           string            `json:"inline_code,omitempty"`
	StorageURI           string            `json:"storage_uri,omitempty"`
	RelativePath         string            `json:"relative_path,omitempty"`
	EntryPoint           string            `json:"entry_point,omitempty"`
	Dependencies         []string          `json:"dependencies,omitempty"`
	TimeoutSeconds       int               `json:"timeout_seconds,omitempty"`
	EnvironmentVariables map[string]string `json:"environment_variables,omitempty"`
}

// ResourceCategory classifies supported context assets based on Gemini upload capabilities.
type ResourceCategory string

const (
	ResourceCategoryUnspecified  ResourceCategory = "RESOURCE_CATEGORY_UNSPECIFIED"
	ResourceCategoryDocumentText ResourceCategory = "RESOURCE_CATEGORY_DOCUMENT_TEXT"
	ResourceCategoryVideo        ResourceCategory = "RESOURCE_CATEGORY_VIDEO"
	ResourceCategoryAudio        ResourceCategory = "RESOURCE_CATEGORY_AUDIO"
	ResourceCategoryImage        ResourceCategory = "RESOURCE_CATEGORY_IMAGE"
	ResourceCategoryCodeRepo     ResourceCategory = "RESOURCE_CATEGORY_CODE_REPO"
)

// ResourceStorageLocation details storage pointers and Gemini Files API references.
type ResourceStorageLocation struct {
	GCSURI             string `json:"gcs_uri,omitempty"`
	PublicURL          string `json:"public_url,omitempty"`
	GeminiFilesAPIName string `json:"gemini_files_api_name,omitempty"`
	GeminiFilesAPIURI  string `json:"gemini_files_api_uri,omitempty"`
	SizeBytes          int64  `json:"size_bytes,omitempty"`
	MIMEType           string `json:"mime_type,omitempty"`
	SHA256Hash         string `json:"sha256_hash,omitempty"`
}

// ResourceInterpretation captures extracted textual representations generated by resource interpreters.
type ResourceInterpretation struct {
	InterpretedText string            `json:"interpreted_text,omitempty"`
	Summary         string            `json:"summary,omitempty"`
	KeyEntities     []string          `json:"key_entities,omitempty"`
	Metadata        map[string]string `json:"metadata,omitempty"`
}

// ResourceRequirement represents a structured context asset required by a skill.
type ResourceRequirement struct {
	ID                 string                   `json:"id"`
	Name               string                   `json:"name"`
	Description        string                   `json:"description,omitempty"`
	Category           ResourceCategory         `json:"category"`
	MIMEType           string                   `json:"mime_type,omitempty"`
	Storage            *ResourceStorageLocation `json:"storage,omitempty"`
	InlineContent      string                   `json:"inline_content,omitempty"`
	Interpretation     *ResourceInterpretation  `json:"interpretation,omitempty"`
	AutoInjectContext bool                     `json:"auto_inject_context,omitempty"`
}

// SkillDefinition represents a loaded enterprise skill definition.
type SkillDefinition struct {
	Name             string                `json:"name"`
	Description      string                `json:"description"`
	Instructions     string                `json:"instructions"`
	License          string                `json:"license,omitempty"`
	Author           string                `json:"author,omitempty"`
	Authors          []AuthorDetails       `json:"authors,omitempty"`
	Version          string                `json:"version,omitempty"`
	Compatibility    string                `json:"compatibility,omitempty"`
	AllowedTools     string                `json:"allowed_tools,omitempty"`
	ToolRequirements []ToolRequirement     `json:"tool_requirements,omitempty"`
	Category         string                `json:"category,omitempty"`
	Tags             []string              `json:"tags,omitempty"`
	TriggerPhrases   []string              `json:"trigger_phrases,omitempty"`
	ExecutionHints   *ExecutionHints       `json:"execution_hints,omitempty"`
	Metadata         map[string]string     `json:"metadata"`
	References       map[string]string     `json:"references"`
	Examples         map[string]string     `json:"examples"`
	Scripts          []ScriptDefinition    `json:"scripts,omitempty"`
	Resources        []ResourceRequirement `json:"resources,omitempty"`
	Path             string                `json:"path"`
	SourceURI        string                `json:"source_uri,omitempty"`
	SHA256Hash       string                `json:"sha256_hash,omitempty"`
}

// GetReferenceContent retrieves content of a reference file on demand.
func (s *SkillDefinition) GetReferenceContent(refName string) string {
	if s.References != nil {
		return s.References[refName]
	}
	return ""
}

// GetExampleContent retrieves content of an example file on demand.
func (s *SkillDefinition) GetExampleContent(exName string) string {
	if s.Examples != nil {
		return s.Examples[exName]
	}
	return ""
}

// ToMap serializes skill definition to a dictionary format matching the Python implementation.
func (s *SkillDefinition) ToMap() map[string]any {
	refKeys := make([]string, 0, len(s.References))
	for k := range s.References {
		refKeys = append(refKeys, k)
	}
	sort.Strings(refKeys)

	exKeys := make([]string, 0, len(s.Examples))
	for k := range s.Examples {
		exKeys = append(exKeys, k)
	}
	sort.Strings(exKeys)

	meta := s.Metadata
	if meta == nil {
		meta = make(map[string]string)
	}

	scripts := s.Scripts
	if scripts == nil {
		scripts = []ScriptDefinition{}
	}

	resources := s.Resources
	if resources == nil {
		resources = []ResourceRequirement{}
	}

	return map[string]any{
		"name":              s.Name,
		"description":       s.Description,
		"instructions":      s.Instructions,
		"license":           s.License,
		"author":            s.Author,
		"authors":           s.Authors,
		"version":           s.Version,
		"compatibility":     s.Compatibility,
		"allowed_tools":     s.AllowedTools,
		"tool_requirements": s.ToolRequirements,
		"category":          s.Category,
		"tags":              s.Tags,
		"trigger_phrases":   s.TriggerPhrases,
		"execution_hints":   s.ExecutionHints,
		"metadata":          meta,
		"references":        refKeys,
		"examples":          exKeys,
		"scripts":           scripts,
		"resources":         resources,
		"path":              s.Path,
		"source_uri":        s.SourceURI,
		"sha256_hash":       s.SHA256Hash,
	}
}

// SkillSummary represents high-level summary metadata for a registered skill.
type SkillSummary struct {
	Name           string   `json:"name"`
	Description    string   `json:"description"`
	ReferenceCount int      `json:"reference_count"`
	ExampleCount   int      `json:"example_count"`
	Path           string   `json:"path"`
	Category       string   `json:"category,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	TriggerPhrases []string `json:"trigger_phrases,omitempty"`
	ScriptCount    int      `json:"script_count,omitempty"`
	ResourceCount  int      `json:"resource_count,omitempty"`
}
