load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "data",
    srcs = [
        "apps_repository.go",
        "database.go",
        "skills_repository.go",
    ],
    importpath = "github.com/retail-cortex/skills/pkg/data",
    deps = [
        "//pkg/model",
        "@com_github_google_uuid//:uuid",
        "@io_gorm_driver_postgres//:postgres",
        "@io_gorm_driver_sqlite//:sqlite",
        "@io_gorm_gorm//:gorm",
        "@io_gorm_gorm//logger",
    ],
)

go_test(
    name = "data_test",
    size = "small",
    srcs = ["data_test.go"],
    deps = [
        ":data",
        "//pkg/model",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
