apiVersion: apps/v1
kind: Deployment
metadata:
  name: castor-registry
  namespace: castor
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: castor-registry
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
