apiVersion: v1
kind: ServiceAccount
metadata:
  name: castor-registry-sa
  namespace: castor
  annotations:
    iam.gke.io/gcp-service-account: castor-registry-dev-sa@PROJECT_ID.iam.gserviceaccount.com
