apiVersion: v1
kind: ServiceAccount
metadata:
  name: skill-service-sa
  namespace: skill-builder
  annotations:
    iam.gke.io/gcp-service-account: skill-service-dev-sa@PROJECT_ID.iam.gserviceaccount.com
