apiVersion: v1
kind: Service
metadata:
  name: castor-registry
  namespace: castor
  labels:
    app.kubernetes.io/name: castor-registry
    app.kubernetes.io/part-of: castor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: castor-registry
  ports:
    - name: http-rest-mcp
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
