# gazelle:ignore
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "registration_v1_proto",
    srcs = [
        "registration_service.proto",
    ],
    strip_import_prefix = "/proto",
)

go_proto_library(
    name = "registration_v1_go_proto",
    importpath = "github.com/retail-cortex/castor/proto/retailcortex/registration/v1",
    proto = ":registration_v1_proto",
)

java_proto_library(
    name = "registration_v1_java_proto",
    deps = [":registration_v1_proto"],
)

py_proto_library(
    name = "registration_v1_py_proto",
    deps = [":registration_v1_proto"],
)

genrule(
    name = "registration_v1_py_grpc_gen",
    srcs = [
        "registration_service.proto",
    ],
    outs = [
        "registration_service_pb2.py",
        "registration_service_pb2.pyi",
        "registration_service_pb2_grpc.py",
    ],
    cmd = """
        uv run --with "grpcio-tools==1.76.0" python3 -m grpc_tools.protoc \\
            -Iproto \\
            --python_out=$(RULEDIR)/../../.. \\
            --pyi_out=$(RULEDIR)/../../.. \\
            --grpc_python_out=$(RULEDIR)/../../.. \\
            $(SRCS)
    """,
    tags = [
        "local",
        "no-sandbox",
    ],
)

py_library(
    name = "registration_v1_py_grpc",
    srcs = [":registration_v1_py_grpc_gen"],
    imports = ["../../.."],
)
