load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "model",
    srcs = [
        "app.go",
        "pagination.go",
        "skill.go",
    ],
    importpath = "github.com/retail-cortex/castor/pkg/model",
)

go_test(
    name = "model_test",
    size = "small",
    srcs = ["pagination_test.go"],
    deps = [
        ":model",
        "@com_github_stretchr_testify//assert",
    ],
)
