baseURL = 'https://retail-cortex.github.io/skills/'
locale = 'en-US'
title = 'Castor Documentation'

theme = 'hugo-geekdoc'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  geekdocRepo = 'https://github.com/retail-cortex/skills'
  geekdocEditPath = 'edit/main/docs/content'
  geekdocSearch = true
